attributes:
  BuildIndependentTargetsInParallel: '1'
  LastSwiftUpdateCheck: '1340'
  LastUpgradeCheck: '1340'
configs:
  Debug: debug
  Release: release
name: idsapp
options:
  minimumXcodeGenVersion: 2.29.0
  defaultConfig: Release
  groupSortPosition: bottom
  transitivelyLinkDependencies: false
  developmentLanguage: en
  xcodeVersion: 13.4
packages:
  SwiftSoup:
    url: https://github.com/scinfu/SwiftSoup
    version: 2.4.3
settings:
  configs:
    Debug:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++17
      IPHONEOS_DEPLOYMENT_TARGET: '15.5'
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
      SWIFT_OPTIMIZATION_LEVEL: -Onone
    Release:
      CLANG_CXX_LANGUAGE_STANDARD: gnu++17
      IPHONEOS_DEPLOYMENT_TARGET: '15.5'
      MTL_FAST_MATH: 'YES'
      SDKROOT: iphoneos
      SWIFT_COMPILATION_MODE: wholemodule
      SWIFT_OPTIMIZATION_LEVEL: -O
targets:
  idsapp:
    platform: iOS
    settings:
      configs:
        Debug:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"idsapp/res/Preview Content"'
          DEVELOPMENT_TEAM: ZVL8YHGVD6
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
          MARKETING_VERSION: 0.1.0
          PRODUCT_BUNDLE_IDENTIFIER: fr.pirids.idsapp
          PRODUCT_NAME: IDS App
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
        Release:
          ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_ASSET_PATHS: '"idsapp/res/Preview Content"'
          DEVELOPMENT_TEAM: ZVL8YHGVD6
          GENERATE_INFOPLIST_FILE: 'YES'
          INFOPLIST_KEY_UIApplicationSceneManifest_Generation: 'YES'
          INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: 'YES'
          INFOPLIST_KEY_UILaunchScreen_Generation: 'YES'
          INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait
            UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft
            UIInterfaceOrientationLandscapeRight
          INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait
          MARKETING_VERSION: 0.1.0
          PRODUCT_BUNDLE_IDENTIFIER: fr.pirids.idsapp
          PRODUCT_NAME: IDS App
          SWIFT_EMIT_LOC_STRINGS: 'YES'
          SWIFT_VERSION: '5.0'
    sources:
    - name: idsapp
      path: idsapp
    type: application
    dependencies:
    - package: SwiftSoup
  idsappTests:
    dependencies:
    - target: idsapp
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: ZVL8YHGVD6
          GENERATE_INFOPLIST_FILE: 'YES'
          IPHONEOS_DEPLOYMENT_TARGET: '15.5'
          MARKETING_VERSION: 0.1.0
          PRODUCT_BUNDLE_IDENTIFIER: fr.pirids.idsappTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/IDS App.app/IDS App
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          BUNDLE_LOADER: $(TEST_HOST)
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: ZVL8YHGVD6
          GENERATE_INFOPLIST_FILE: 'YES'
          IPHONEOS_DEPLOYMENT_TARGET: '15.5'
          MARKETING_VERSION: 0.1.0
          PRODUCT_BUNDLE_IDENTIFIER: fr.pirids.idsappTests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_HOST: $(BUILT_PRODUCTS_DIR)/IDS App.app/IDS App
    sources:
    - name: idsappTests
      path: idsappTests
    type: bundle.unit-test
  idsappUITests:
    dependencies:
    - target: idsapp
    platform: iOS
    settings:
      configs:
        Debug:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: ZVL8YHGVD6
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: 0.1.0
          PRODUCT_BUNDLE_IDENTIFIER: fr.pirids.idsappUITests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_TARGET_NAME: idsapp
        Release:
          ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: 'YES'
          CODE_SIGN_STYLE: Automatic
          CURRENT_PROJECT_VERSION: '1'
          DEVELOPMENT_TEAM: ZVL8YHGVD6
          GENERATE_INFOPLIST_FILE: 'YES'
          MARKETING_VERSION: 0.1.0
          PRODUCT_BUNDLE_IDENTIFIER: fr.pirids.idsappUITests
          SWIFT_EMIT_LOC_STRINGS: 'NO'
          SWIFT_VERSION: '5.0'
          TEST_TARGET_NAME: idsapp
    sources:
    - name: idsappUITests
      path: idsappUITests
    type: bundle.ui-testing
